---

- name: List indexes
  uri: 
    url: "{{ endpoint }}"
    method: GET
    return_content: yes
    validate_certs: "{{ validate_certs }}"
  register: result
  delegate_to: localhost

- debug:
    msg: "{{ result['content'] }}"