---

- name: Check task has been provided
  assert:
    that:
      - task != ""
    msg: "Task is mandatory"
  tags: [ "check_vars" ]

- name: Include task specific vars
  include_vars:
    file: vars/{{ task }}.yml
  tags: always

- include: "{{ task }}.yml"


#@todo make cert validation optional