#https://stackoverflow.com/questions/29508955/elasticsearch-reindexing-your-data-with-zero-downtime

- name: Check vars are defined
  assert:
    that:
      - source_index is defined and source_index != ""
      - dest_index is defined and dest_index != ""
      - alias is defined and alias != ""
    msg: "source_index/dest_index/alias is/are missing"
  tags: [ "check_vars" ]

# - name: Check that the number of shards > 0
#   assert:
#     that:
#       - shards is defined and shards | int > 1
#     msg: "The number of shards must be > 1, got {{ shards }}"
#   tags: [ "check_vars" ]

# - name: Check that the number of replicas >= 0
#   assert:
#     that:
#       - shards is defined and shards | int >= 0
#     msg: "The number of replicas must be >= 0, got {{ replicas }}"
#   tags: [ "check_vars" ]

- name: Move alias
  uri: 
    url: "{{ endpoint }}"
    method: POST
    body: "{{ query }}"
    body_format: json
  delegate_to: localhost