---

- name: Check that the index name is defined
  assert:
    that:
      - index is defined and index != ""
      - datafile is defined and datafile != ""
    msg: "Index/data-file is/are missing"
  tags: [ "check_vars" ]

- name: Create index
  uri: 
    url: "{{ endpoint }}"
    method: POST
    body: "{{ query }}"
    body_format: json