---

- name: Check variables are defined
  assert:
    that:
      - index is defined and index != ""
      - data_file is defined and data_file != ""
    msg: "Index/data_file is/are missing"
  tags: [ "check_vars" ]

# Results in OOM error
# - name: Dump data using bulk API 
#   uri: 
#     url: "{{ endpoint }}"
#     method: POST
#     body: "{{ query }}"
#     body_format: json

# Results in OOM error
- name: Dump data using bulk API
  shell: curl -X POST "{{ endpoint }}/_doc/_bulk?pretty&refresh" --data-binary "{{ query }}" 