---

- name: Check that the index name is defined
  assert:
    that:
      - index is defined and index != ""
      - mapping_file is defined and mapping_file != ""
    msg: "index/mapping-file is/are missing"
  tags: [ "check_vars" ]

# - name: Check that the number of shards > 0
#   assert:
#     that:
#       - shards is defined and shards | int > 1
#     msg: "The number of shards must be > 1, got {{ shards }}"
#   tags: [ "check_vars" ]

# - name: Check that the number of replicas >= 0
#   assert:
#     that:
#       - shards is defined and shards | int >= 0
#     msg: "The number of replicas must be >= 0, got {{ replicas }}"
#   tags: [ "check_vars" ]

- name: Create index
  uri: 
    url: "{{ endpoint }}"
    method: PUT
    body: "{{ query }}"
    body_format: json